areas: []
disc: [33.0, 33.0]
players:
- label: '2'
  orientation: -30.465544919459884
  pos: [32.5, 32.5]
  role: o
- label: '2'
  orientation: -116
  pos: [31.5, 33.0]
  role: d
- label: '1'
  orientation: -66
  pos: [25.0, 33.0]
  role: o
- label: '1'
  orientation: 139
  pos: [26.0, 34.0]
  role: d
- label: '3'
  orientation: 149
  pos: [19.0, 36.5]
  role: d
- label: '3'
  orientation: -82
  pos: [17.5, 34.5]
  role: o
