areas: []
disc: [8.5, 26.0]
players:
- label: '3'
  orientation: -120
  pos: [21.0, 31.5]
  role: d
- label: '2'
  orientation: 135
  pos: [10.0, 28.0]
  role: d
- label: '3'
  orientation: 131
  pos: [22.5, 27.5]
  role: o
- label: '1'
  orientation: 33
  pos: [17.5, 23.5]
  role: d
- label: '1'
  orientation: 23
  pos: [16.5, 24.0]
  role: o
- label: '2'
  orientation: 130.6012946450045
  pos: [9.5, 26.0]
  role: o
