areas: []
disc: [13.5, 23.5]
players:
- label: '1'
  orientation: 5
  pos: [13.0, 23.0]
  role: o
- label: '1'
  orientation: -135
  pos: [12.5, 24.0]
  role: d
- label: '3'
  orientation: -180
  pos: [22.0, 40.5]
  role: o
- label: '3'
  orientation: 14
  pos: [22.0, 39.0]
  role: d
- label: '2'
  orientation: 0
  pos: [21.5, 22.5]
  role: o
- label: '2'
  orientation: -108
  pos: [20.0, 23.0]
  role: d
- label: '4'
  orientation: -15.255118703057777
  pos: [13.5, 41.5]
  role: o
- label: '4'
  orientation: -7.125016348901798
  pos: [14.5, 41.5]
  role: d
