areas: []
disc: [15.0, 71.5]
players:
- label: '2'
  orientation: -180
  pos: [19.0, 90.0]
  role: o
- label: '3'
  orientation: -180
  pos: [19.0, 92.5]
  role: o
- label: '4'
  orientation: 176
  pos: [19.0, 95.0]
  role: o
- label: '2'
  orientation: 40
  pos: [20.0, 89.0]
  role: d
- label: '3'
  orientation: 39
  pos: [20.0, 91.5]
  role: d
- label: '4'
  orientation: 60
  pos: [20.0, 94.5]
  role: d
- label: '7'
  orientation: 90
  pos: [15.5, 71.0]
  role: o
- label: '6'
  orientation: -165
  pos: [20.0, 70.5]
  role: o
- label: '6'
  orientation: -147
  pos: [19.5, 73.5]
  role: d
- label: '7'
  orientation: 78
  pos: [13.0, 73.5]
  role: d
- label: '1'
  orientation: 86.82016988013577
  pos: [10.0, 85.5]
  role: o
- label: '1'
  orientation: 85.60129464500447
  pos: [13.5, 84.5]
  role: d
- label: '5'
  orientation: -30
  pos: [23.5, 87.5]
  role: o
- label: '5'
  orientation: -34
  pos: [23.0, 84.5]
  role: d
