areas: []
disc: [28.0, 32.0]
players:
- label: '1'
  orientation: -71
  pos: [34.5, 23.0]
  role: d
- label: '1'
  orientation: 90
  pos: [35.5, 23.5]
  role: o
- label: '2'
  orientation: 108
  pos: [28.5, 32.0]
  role: o
- label: '3'
  orientation: 120
  pos: [22.5, 27.0]
  role: d
- label: '3'
  orientation: -30
  pos: [21.5, 27.0]
  role: o
- label: '2'
  orientation: 99
  pos: [32.5, 32.0]
  role: d
