areas: []
disc: [16.0, 33.0]
players:
- label: '1'
  orientation: -135
  pos: [34.5, 24.0]
  role: d
- label: '1'
  orientation: 90
  pos: [35.5, 23.5]
  role: o
- label: '2'
  orientation: 108
  pos: [28.5, 32.0]
  role: o
- label: '2'
  orientation: 85
  pos: [30.0, 32.0]
  role: d
- label: '3'
  orientation: 56
  pos: [19.0, 29.5]
  role: d
- label: '3'
  orientation: 32.47119229084849
  pos: [16.5, 32.5]
  role: o
